jobs:
- job: Build

  pool:
    vmImage: 'ubuntu-latest'

  variables:
  - group: moc-build
  - name: GO111MODULE
    value: 'on'
  - name: GDN_VERSION
    value: '0.110.0-linux'
  - name: GDNP_VERSION
    value: '1.61.0-linux'
  - name: LGTM.UploadSnapshot
    value: true

  steps:
  - script: |
      echo "Removing existing Go installation"
      sudo rm -rf /usr/local/go
      echo "Downloading Go from Microsoft URL"
      # Latest download link can be found at https://raw.githubusercontent.com/microsoft/go/refs/heads/microsoft/main/eng/doc/release-branch-links.json
      curl -L -o go.tar.gz "https://aka.ms/golang/release/latest/go1.26.linux-amd64.tar.gz"
      echo "Extracting Go"
      sudo tar -C /usr/local -xzf go.tar.gz
      echo "Adding Go to PATH"
      echo "##vso[task.prependpath]/usr/local/go/bin"
      export PATH=/usr/local/go/bin:$PATH
      echo "Verifying Go installation"
      go version
    displayName: "Install Microsoft Go"
  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: '$(KNOWN_HOST)' 
      sshPublicKey: '$(SSH_PUBLIC_KEY)'
      sshKeySecureFile: 'azure-pipelines-ssh-key-new'
  - script: |
      git config --global url.ssh://git@github.com/.insteadOf https://github.com/
    displayName: 'Set up the Go workspace'

  - script: |
      sudo apt-get install gcc-mingw-w64

      # Static binary workaround for CodeQL and Go 1.21 and higher
      # https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/troubleshooting/onboarding/language-compiled
      mkdir $AGENT_TEMPDIRECTORY/codeql-go-tracing
      WORKAROUND_DIR=$AGENT_TEMPDIRECTORY/codeql-go-tracing
      WHICH_GO=$(which go)
      cat > "${WORKAROUND_DIR}/go" <<EOF
      #!/bin/bash
      exec $WHICH_GO "\$@"
      EOF

      chmod 755 "${WORKAROUND_DIR}/go"
      export PATH="${WORKAROUND_DIR}:${PATH}"

      mkdir manifest
      make all
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: 'Build'

  - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
    displayName: 'SBOM Generation'
    inputs:
      BuildDropPath: $(System.DefaultWorkingDirectory)/manifest

  - publish: $(System.DefaultWorkingDirectory)/bin
    artifact: binaries
  - publish: $(System.DefaultWorkingDirectory)/manifest
    artifact: manifest

- job: Lint
  displayName: 'Lint'

  pool:
    vmImage: 'ubuntu-latest'

  variables:
  - group: moc-build
  - name: GO111MODULE
    value: 'on'

  steps:
  - script: |
      echo "Removing existing Go installation"
      sudo rm -rf /usr/local/go
      echo "Downloading Go from Microsoft URL"
      # Latest download link can be found at https://raw.githubusercontent.com/microsoft/go/refs/heads/microsoft/main/eng/doc/release-branch-links.json
      curl -L -o go.tar.gz "https://aka.ms/golang/release/latest/go1.26.linux-amd64.tar.gz"
      echo "Extracting Go"
      sudo tar -C /usr/local -xzf go.tar.gz
      echo "Adding Go to PATH"
      echo "##vso[task.prependpath]/usr/local/go/bin"
      export PATH=/usr/local/go/bin:$PATH
      echo "Verifying Go installation"
      go version
    displayName: "Install Microsoft Go"

  - script: |
      make golangci-lint
    displayName: 'Run GolangCI-Lint'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
